!include common.yaml
---
- package: Prodigal 
  name: prodigal 
  version: "{{versions.prodigal}}"
  vendor_source: https://github.com/hyattpd/Prodigal/archive/v{{version}}.{{extension}}
  description: |
    Prodigal {{version}} is a protein-coding gene prediction software tool for
    bacterial and archaeal genomes. The acronym stands for PROkaryotic DYnamic
    Programming Genefinding ALgorithm. See https://github.com/hyattpd/Prodigal
  src_dir: "{{package}}-{{version}}"
  build:
    modules: 
      - "{{compiler}}/{{compiler_version}}"
    pkgmake: make
  extras: LICENSE README.md
  install:
     makeinstall: >
       mkdir -p $(ROOT){{root}}/bin;
       $(INSTALL) -m 755 {{name}} $(ROOT){{root}}/bin
